# Generated by Django 4.2 on 2023-11-01 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='gang',
            field=models.CharField(blank=True, default='Ingen', max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='room_number',
            field=models.PositiveSmallIntegerField(blank=True, default='999'),
        ),
        migrations.CreateModel(
            name='MemberVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.question')),
            ],
            options={
                'unique_together': {('member', 'question')},
            },
        ),
    ]
