# Generated by Django 3.2.20 on 2023-11-18 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_member_gang_alter_member_room_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membervote',
            name='choice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.choice'),
            preserve_default=False,
        ),
    ]
